spring:
  # 데이터베이스 설정
  datasource:
    # Docker Compose에서 환경 변수로 설정되므로 여기서는 기본값만 제공
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      initialization-fail-timeout: 60000
      connection-timeout: 60000
      maximum-pool-size: 5

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update # 개발 환경에서는 update, 운영 환경에서는 validate 권장
    show-sql: true # 개발 환경에서만 true로 설정
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false # 성능 향상을 위해 false로 설정
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC
  # 메일 설정
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
jwt:
  secret: ${JWT_SECRET}
